### ISSUE TITLE
Card Object Lacks Image Parameters

### ISSUE THREAD

**Issue by cryptogramllc** [nickclaw/alexa-ability#1]
The card request object within the Request.js file does not allocate any parameters for the image urls. For instance, Alexa can receive parameters for images with in card object like so: 
"image": {
        "smallImageUrl": "string",
        "largeImageUrl": "string"
}

**Comment by nickclaw** [comment]
👍  I'll try to get this in tonight.

**Comment by nickclaw** [comment]
Here you go @cryptogramllc

https://github.com/nickclaw/alexa-ability/blob/master/docs/api/Request.md#showcard---request

Feel free to let me know if you have any comments/questions about alexa-ability!
